### ISSUE TITLE
crash when decode h264

### ISSUE THREAD

**Issue by waiter89** [01org/libyami#878]
(gdb) bt
#0  __gnu_cxx::__atomic_add_dispatch (__val=1, __mem=0x3d) at /usr/include/c++/4.8/ext/atomicity.h:96
#1  std::tr1::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_add_ref_copy (this=0x35) at /usr/include/c++/4.8/tr1/shared_ptr.h:128
#2  std::tr1::__shared_count<(__gnu_cxx::_Lock_policy)2>::__shared_count (__r=..., this=0x7f693c052da8) at /usr/include/c++/4.8/tr1/shared_ptr.h:348
#3  std::tr1::__shared_ptr<YamiMediaCodec::VaapiDecPictureH264, (__gnu_cxx::_Lock_policy)2>::__shared_ptr (this=0x7f693c052da0)
    at /usr/include/c++/4.8/tr1/shared_ptr.h:541
#4  std::tr1::shared_ptr<YamiMediaCodec::VaapiDecPictureH264>::shared_ptr (this=0x7f693c052da0) at /usr/include/c++/4.8/tr1/shared_ptr.h:985
#5  std::_Construct<std::tr1::shared_ptr<YamiMediaCodec::VaapiDecPictureH264>, std::tr1::shared_ptr<YamiMediaCodec::VaapiDecPictureH264> > (__value=..., 
    __p=0x7f693c052da0) at /usr/include/c++/4.8/bits/stl_construct.h:83
#6  std::__uninitialized_copy<false>::__uninit_copy<std::tr1::shared_ptr<YamiMediaCodec::VaapiDecPictureH264>*, std::tr1::shared_ptr<YamiMediaCodec::VaapiDecPictureH264>*>
    (__result=0x7f693c052d90, __last=0x7f693c03b000, __first=0x7f693c03aff0) at /usr/include/c++/4.8/bits/stl_uninitialized.h:75
#7  std::uninitialized_copy<std::tr1::shared_ptr<YamiMediaCodec::VaapiDecPictureH264>*, std::tr1::shared_ptr<YamiMediaCodec::VaapiDecPictureH264>*> (
    __result=0x7f693c052d90, __last=0x7f693c03b000, __first=0x7f693c03afe0) at /usr/include/c++/4.8/bits/stl_uninitialized.h:117
#8  std::__uninitialized_copy_a<std::tr1::shared_ptr<YamiMediaCodec::VaapiDecPictureH264>*, std::tr1::shared_ptr<YamiMediaCodec::VaapiDecPictureH264>*, std::tr1::shared_ptr
<YamiMediaCodec::VaapiDecPictureH264> > (__result=0x7f693c052d90, __last=0x7f693c03b000, __first=0x7f693c03afe0) at /usr/include/c++/4.8/bits/stl_uninitialized.h:258
#9  std::__uninitialized_move_if_noexcept_a<std::tr1::shared_ptr<YamiMediaCodec::VaapiDecPictureH264>*, std::tr1::shared_ptr<YamiMediaCodec::VaapiDecPictureH264>*, std::all
ocator<std::tr1::shared_ptr<YamiMediaCodec::VaapiDecPictureH264> > > (__alloc=..., __result=0x7f693c052d90, __last=0x7f693c03b000, __first=0x7f693c03afe0)
    at /usr/include/c++/4.8/bits/stl_uninitialized.h:281
#10 std::vector<std::tr1::shared_ptr<YamiMediaCodec::VaapiDecPictureH264>, std::allocator<std::tr1::shared_ptr<YamiMediaCodec::VaapiDecPictureH264> > >::_M_insert_aux (
    this=0x3216a10, __position=..., __x=...) at /usr/include/c++/4.8/bits/vector.tcc:362
#11 0x00007f69671234f1 in std::vector<std::tr1::shared_ptr<YamiMediaCodec::VaapiDecPictureH264>, std::allocator<std::tr1::shared_ptr<YamiMediaCodec::VaapiDecPictureH264> > 
>::insert (this=this@entry=0x3216a10, __position=..., __x=...) at /usr/include/c++/4.8/bits/vector.tcc:127
#12 0x00007f696711daf1 in YamiMediaCodec::VaapiDecoderH264::DPB::modifyReferenceList (this=this@entry=0x3216a10, picture=..., slice=slice@entry=0x7f693c060590, 
    refList=..., refIdx=refIdx@entry=0 '\000') at vaapidecoder_h264.cpp:660
#13 0x00007f69671206ec in YamiMediaCodec::VaapiDecoderH264::DPB::initReference (this=this@entry=0x3216a10, picture=..., slice=slice@entry=0x7f693c060590)
    at vaapidecoder_h264.cpp:587
#14 0x00007f6967120b46 in YamiMediaCodec::VaapiDecoderH264::decodeSlice (this=this@entry=0x3216810, nalu=nalu@entry=0x7f69583be710) at vaapidecoder_h264.cpp:1746
#15 0x00007f6967120d46 in YamiMediaCodec::VaapiDecoderH264::decodeNalu (this=this@entry=0x3216810, nalu=nalu@entry=0x7f69583be710) at vaapidecoder_h264.cpp:1760
#16 0x00007f6967120f03 in YamiMediaCodec::VaapiDecoderH264::decode (this=0x3216810, buffer=0x7f69583be7d0) at vaapidecoder_h264.cpp:1833
#17 0x00007f69670df9e5 in YamiEncoderInput::ConsumeVideo (this=0x3216720, Apbuf=<optimized out>, Alen=<optimized out>, Aflag=<optimized out>) at ../yamidecoder.cpp:132
#18 0x00007f69677fb348 in ff_inputer_consume (Ainputer=0x3216fe0, Apbuf=0x7f68fc00d620, Alen=27836, Aflag=0) at ../encoder.cpp:317
#19 0x00007f696ccc08ba in pc_inputer_consume (Ainputer=0x3216fe0, Apbuf=0x7f68fc00d620, Alen=27836, Aflag=0) at ../shanwei_proc/shanwei_proc.c:619
#20 0x00007f69656caf3a in VideoEncoder::Draw (this=0x3223760, Aspot=0x3216fe0, Abuf=0x7f68fc00d620, Alen=27836, Aflag=0) at VideoEncoder.cpp:67

**Comment by xuguangxin** [comment]
Could you share the clip to us?
thanks
